mascotas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import logout_then_login, login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required
from usuario.views import CustomLoginView
from usuario.views import customlogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pet/', include('refuge.urls')),
    path('user/', include('usuario.urls')),
    path('reset/password_reset', password_reset, {'template_name': 'recover_password/password_reset_form.html',
                                                  'email_template_name': 'recover_password/password_reset_email.html'}, name='password_reset'),

    path('reset/password_reset_done', password_reset_done,
         {'template_name': 'recover_password/password_reset_done.html'}, name='password_reset_done'),

    path('reset/<uidb64>/<token>/ ', password_reset_confirm, {
         'template_name': 'recover_password/password_reset_confirm.html'}, name='password_reset_confirm'),
    path('reset/password_reset_complete', password_reset_complete,
         {'template_name': 'recover_password/password_reset_complete.html'}, name='password_reset_complete'),

    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', customlogout, name='logout'),


]

refuge/urls.py
from django.urls import path
from . import views


app_name = 'refuge'
urlpatterns = [
    path('', views.index, name='index'),
    path('list.json/', views.list_pet, name='pet_list_json'),
    path('list/', views.PetListView.as_view(), name='pet_list'),
    path('create/', views.PetCreateView.as_view(), name='pet_create'),
    path('update/<int:pk>/', views.PetUpdateView.as_view(), name='pet_update'),
    path('delete/<int:pk>/', views.PetDeleteView.as_view(), name='pet_delete'),

    path('adoption/list/', views.AdoptionListView.as_view(), name='adoption_list'),
    path('adoption/create/', views.AdoptionCreateView.as_view(), name='adoption_create'),
    path('adoption/update/<int:pk>/',
         views.AdoptionUpdateView.as_view(), name='adoption_update'),
    path('adoption/delete/<int:pk>/',
         views.AdoptionDeleteView.as_view(), name='adoption_delete'),
    path('person/list.json', views.list_person, name='person_list_json'),
    path('person/list/', views.view_person, name='person_list'),
    path('vaccine/autocomplete/', views.VaccineAutocompleteView.as_view(),
         name='vaccine_autocomplete'),
    path('pet/autocomplete/', views.PetAutocompleteView.as_view(),
         name='pet_autocomplete'),

    path('person/autocomplete/', views.PersonAutocompleteView.as_view(),
         name='person_autocomplete'),
    path('create_instance/',views.create_instance_example,name='create_instance'),


]

templates/pet/index.html
{% extends 'base/base.html' %} {% load staticfiles %} {% block title %} Welcome {% endblock%} {% block content %}
<h4 class="display-2">ADOPTA UNA MASCOTA Y SE FELIZ (:</h4>

<button id="btn_create_instance" class="btn btn-success">CREAR UNA INSTANCIA</button>

<button id="btn_update_variables" class="btn btn-danger">actualizar variables</button>

<script src="{% static 'js/require.js' %}"></script>


 {% endblock %}

templates/pet/pet_delete.html
{% extends 'base/base.html' %} 
{% block title %} Pet Delete {% endblock%}
{%block content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>¿Desea elimiar el registro de {{object.name}}</h3>
    <button class="btn btn-danger" name="delete" type="submit">Si,Eliminar </button>
    <a class="btn btn-success" name="cancel" href="{% url 'refuge:pet_list' %}">Cancelar </a>
</form>
{% endblock %}

templates/pet/pet_list.html
{% extends 'base/base.html' %} 
{% block title %} Pet List {% endblock%}
{% block content %}
<div class="container mt-3">
    <h2>MASCOTAS EN REFUGIO</h2>
    <p>una lista de todas las mascotas que estan en el refugio</p>
    <input class="form-control" id="myInput" type="text" placeholder="Search..">
    <br>
    <table name="table" class="table table-bordered table-dark table-hover table-responsive">
        <thead class="">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Sexo</th>
                <th>Edad</th>
                <th>Fecha de Rescate</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody id="myTable">
            {% if object_list %} {% for pet in object_list %}
            <tr>
                <th>{{pet.id}}</th>
                <th>{{pet.name}}</th>
                <th>{{pet.sex}}</th>
                <th>{{pet.age}}</th>
                <th>{{pet.rescue_date}}</th>
                <th>
                    
                    <a class="btn btn-primary" name="edit" href="{% url 'refuge:pet_update' pet.id%}">Editar</a>
                    <a class="btn btn-danger" name="delete" href="{% url 'refuge:pet_delete' pet.id%}">Eliminar</a> 
                </th>
            </tr>
            {% endfor %} {% else %}
            <h1>NO HAY REGISTROS</h1> {% endif %}
        </tbody>
    </table>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
        {%endif%} {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
        {%endif%}
    </ul>
</div>

{% endblock %}