mascotas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import logout_then_login, login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required
from usuario.views import CustomLoginView
from usuario.views import customlogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pet/', include('refuge.urls')),
    path('user/', include('usuario.urls')),
    path('reset/password_reset', password_reset, {'template_name': 'recover_password/password_reset_form.html',
                                                  'email_template_name': 'recover_password/password_reset_email.html'}, name='password_reset'),

    path('reset/password_reset_done', password_reset_done,
         {'template_name': 'recover_password/password_reset_done.html'}, name='password_reset_done'),

    path('reset/<uidb64>/<token>/ ', password_reset_confirm, {
         'template_name': 'recover_password/password_reset_confirm.html'}, name='password_reset_confirm'),
    path('reset/password_reset_complete', password_reset_complete,
         {'template_name': 'recover_password/password_reset_complete.html'}, name='password_reset_complete'),

    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', customlogout, name='logout'),


]

refuge/urls.py
from django.urls import path
from . import views


app_name = 'refuge'
urlpatterns = [
    path('', views.index, name='index'),
    path('list.json/', views.list_pet, name='pet_list_json'),
    path('list/', views.PetListView.as_view(), name='pet_list'),
    path('create/', views.PetCreateView.as_view(), name='pet_create'),
    path('update/<int:pk>/', views.PetUpdateView.as_view(), name='pet_update'),
    path('delete/<int:pk>/', views.PetDeleteView.as_view(), name='pet_delete'),

    path('adoption/list/', views.AdoptionListView.as_view(), name='adoption_list'),
    path('adoption/create/', views.AdoptionCreateView.as_view(), name='adoption_create'),
    path('adoption/update/<int:pk>/',
         views.AdoptionUpdateView.as_view(), name='adoption_update'),
    path('adoption/delete/<int:pk>/',
         views.AdoptionDeleteView.as_view(), name='adoption_delete'),
    path('person/list.json', views.list_person, name='person_list_json'),
    path('person/list/', views.view_person, name='person_list'),
    path('vaccine/autocomplete/', views.VaccineAutocompleteView.as_view(),
         name='vaccine_autocomplete'),
    path('pet/autocomplete/', views.PetAutocompleteView.as_view(),
         name='pet_autocomplete'),

    path('person/autocomplete/', views.PersonAutocompleteView.as_view(),
         name='person_autocomplete'),
    path('create_instance/',views.create_instance_example,name='create_instance'),


]

refuge/models.py
from django.db import models
from django.conf import settings


class Person(models.Model):
    name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=70)
    age = models.PositiveIntegerField()
    phone = models.CharField(max_length=12)
    email = models.EmailField(unique=True)
    home = models.TextField()

    def __str__(self):
        return f'{self.name} {self.last_name}'


class Vaccine(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Pet(models.Model):
    vaccine = models.ManyToManyField(Vaccine, blank=True)
    name = models.CharField(max_length=50)
    sex = models.CharField(max_length=10)
    age = models.PositiveIntegerField()
    rescue_date = models.DateField()
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class PetCharacteristic(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    key = models.CharField(max_length=300)
    value = models.CharField(max_length=200)

    class Meta:
        verbose_name = "PetCharacteristic"
        verbose_name_plural = "PetCharacteristics"

    def __str__(self):
        return f'{self.key} {self.value}'


class AdoptionApplication(models.Model):
    person = models.ForeignKey(
        Person, null=False, blank=False, on_delete=models.CASCADE)
    reasons = models.TextField()
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.reasons

    def get_adoption(user):
        return AdoptionApplication.objects.filter(
            created_by=user).order_by('id')

templates/form/form.html
{% extends 'base/base.html' %} {% load formset_tags %} {% block title %} Form {% endblock%} {%block content %}
<form name="data-form" action="" method="post">
    {% csrf_token %}
    <br>
    <div class="container">
        {% if form2%} {% for item in form2%}
        <div class="row">
            <div class="col-xs-offset-2 col-10">
                <div class="form-group form">
                    <label for="{item.name}}">{{item.label}} </label>
                    {{item}}
                </div>
            </div>
        </div>
        {% endfor %} {% endif %} {% if form%} {% for item in form%}
        <div class="row">
            <div class="col-xs-offset-2 col-10">
                <div class="form-group form1">
                    <label for="{item.name}}">{{item.label}} </label>
                    {{item}}
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="justify-content-center">
            <h3>Caracteristicas de la mascota</h3>
        </div>



        <div id="formset" data-formset-prefix="{{ formset.prefix }}">
            {{ formset.management_form }}
            <div data-formset-body>
                <!-- New forms will be inserted in here -->
                {% for form in formset %}
                
                    <div class="row justify-content-left ">
                        <div data-formset-form>
                        {{ form }}
                    </div>
                </div>
                {% endfor %}
            </div>
            <script type="form-template" data-formset-empty-form>
                {% escapescript %}
                <div class="row justify-content-left ">
                <div data-formset-form>                    
                    {{ formset.empty_form }}
                </div>
                </div>
                {% endescapescript %}
            </script>
            <!-- This button will add a new form when clicked -->
            <input type="button" value="Add another" data-formset-add>
            <script>
            jQuery(function($) {
                $("#formset").formset({
                    animateForms: true,
                    reorderMode: 'dom',
                });
            });
            </script>
        </div>
        {% endif %}
    </div>
    <input type="hidden" id="person_pk" name="person_pk">
    <div class="row justify-content-center ">
        <button class="col-2 btn btn-success" id="save" name="save"> Guardar </button>
    </div>
    <br>
</form>
{{ form.media }} {{ form2.media }} {{ formset.media }}
<script>
$("#id_email").blur(function() {
    let email = $("#id_email").val()
    $('#person_pk').val("");
    $.ajax({
            url: '{% url "refuge:person_list_json" %}',
            type: 'GET',
            dataType: 'json',
            data: { "email": email },
        })

        .done(function(data) {
            console.log(data);
            add(data);
        })
        .fail(function() {
            console.log("error");
        })
        .always(function() {
            console.log("complete");
        });


});

function add(data) {

    let fields = []
    $(".form input").each(function() {
        let element_html_name = $(this).attr('name');
        if (element_html_name != "email") {
            $("#id_" + element_html_name).val("");
            fields.push(element_html_name);
        }



    });

    fields.push('home');
    $("#id_home").val("");

    $.each(data, function(index, item) {
        for (var i = 0; i < fields.length; i++) {
            $("#id_" + fields[i]).val(item['fields'][fields[i]]);

        }
        $('#person_pk').val(item['pk']);
    });

}
</script>
<br>
<br> {% endblock %}