mascotas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import logout_then_login, login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth.decorators import login_required
from usuario.views import CustomLoginView
from usuario.views import customlogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pet/', include('refuge.urls')),
    path('user/', include('usuario.urls')),
    path('reset/password_reset', password_reset, {'template_name': 'recover_password/password_reset_form.html',
                                                  'email_template_name': 'recover_password/password_reset_email.html'}, name='password_reset'),

    path('reset/password_reset_done', password_reset_done,
         {'template_name': 'recover_password/password_reset_done.html'}, name='password_reset_done'),

    path('reset/<uidb64>/<token>/ ', password_reset_confirm, {
         'template_name': 'recover_password/password_reset_confirm.html'}, name='password_reset_confirm'),
    path('reset/password_reset_complete', password_reset_complete,
         {'template_name': 'recover_password/password_reset_complete.html'}, name='password_reset_complete'),

    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', customlogout, name='logout'),


]

refuge/urls.py
from django.urls import path
from . import views


app_name = 'refuge'
urlpatterns = [
    path('', views.index, name='index'),
    path('list.json/', views.list_pet, name='pet_list_json'),
    path('list/', views.PetListView.as_view(), name='pet_list'),
    path('create/', views.PetCreateView.as_view(), name='pet_create'),
    path('update/<int:pk>/', views.PetUpdateView.as_view(), name='pet_update'),
    path('delete/<int:pk>/', views.PetDeleteView.as_view(), name='pet_delete'),

    path('adoption/list/', views.AdoptionListView.as_view(), name='adoption_list'),
    path('adoption/create/', views.AdoptionCreateView.as_view(), name='adoption_create'),
    path('adoption/update/<int:pk>/',
         views.AdoptionUpdateView.as_view(), name='adoption_update'),
    path('adoption/delete/<int:pk>/',
         views.AdoptionDeleteView.as_view(), name='adoption_delete'),
    path('person/list.json', views.list_person, name='person_list_json'),
    path('person/list/', views.view_person, name='person_list'),
    path('vaccine/autocomplete/', views.VaccineAutocompleteView.as_view(),
         name='vaccine_autocomplete'),
    path('pet/autocomplete/', views.PetAutocompleteView.as_view(),
         name='pet_autocomplete'),

    path('person/autocomplete/', views.PersonAutocompleteView.as_view(),
         name='person_autocomplete'),
    path('create_instance/',views.create_instance_example,name='create_instance'),


]

templates/adoption/AdoptionList.html
{% extends 'base/base.html' %} 
{% block title %} Adoption List {% endblock%}
{% block content %}
<div class="container">
    <h2>LISTA DE SOLICITUDES</h2>
    <p>una lista de todas las Adopciones Hechas</p>
    <table name="table" class="table table-dark table-hover">
        <thead>
            <tr>
                <th>folio. Adopcion</th>
                <th>Adoptante</th>
                <th>Razones De Adopcion</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% if object_list %} {% for adop in object_list %}
            <tr>
                <th>{{adop.id}}</th>
                <th>{{adop.person.name}} {{adop.person.last_name}}</th>
                <th>{{adop.reasons}}</th>
                <th>
                    {% if adop.created_by == user %}
                    <a class="btn btn-primary" name="edit" href="{% url 'refuge:adoption_update' adop.id %}">Editar</a>
                    <a class="btn btn-danger" name="delete" href="{% url 'refuge:adoption_delete' adop.id %}">Eliminar</a> {% endif %}
                </th>
            </tr>
            {% endfor %} {% else %}
            <h1>NO HAY REGISTROS DE SOLICITUDES</h1> {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/adoption/adoption_delete.html
{% extends 'base/base.html' %}
{% block title %} Adoption Delete {% endblock%}
 {%block content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>¿Desea elimiar el registro de {{object.people.name}} {{object.people.last_name}}</h3>
    <button class="btn btn-danger" name="delete" type="submit">Si,Eliminar </button>
    <a class="btn btn-success" name="cancel" href="{% url 'refuge:adoption_list' %}">Cancelar </a>
</form>
{% endblock %}